language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: KBpzE5ISUSKbc+IRFLZIlisjKT41DKL83SPfCVyxwHjkbk3Q2+OS/FsGns/QE5VhgxIQdSzRfnM1LOSLM01UEmmb404sSiC9PHVESrdc3NS+jJWoqoACq6fKwF+s/1aBkPNBRBq4DUoAyhjI6JAJvLWP83f4vBQ8TqhjMhZokHN8/NrCRH6YVuBKKw0/GS9URTeBFrmTNhCCtQ6sMYCosBUIZK9c1iLsrulVUy+pPaC9f9FWPS/pBZXH2WKJqTVW1Uvo7y7u+3IvjnCssZZDVQ5Zfz8Tuyux7Df3y7T9qEQHAh/BJJiEU2t+7fcMFKYma7pJUdOwgrA4OAQVfPEc+srfdNsxmhdNnY1XYXDl3MGs3PoIjfkUYPwq7g02aUPkXMOxvQDZlanvRIwpQF+1eliat5xzjt2+XKUj8zrD6sDs54t/mUQ4r9SzBHGw1UJkC3eVcDzo+CiFlYS4z8lZRVDmuAwvBc0oY9L7Zu73ES7y0GJ7a9AEla7hMHYydv3mPZf9rH1s30VAndCCPYNbv7r386iyg43kRB5uLnYF7WqlAxpZTOhRkwf4tiGOfah8tnviLTSFM6gPgluDQFwFnVYrYim4h/SoUjFRFq3xlIO/y1gRSJG2PDFvX9IjaU/w9IJsBCLLiFUwhaMbYiR7C24PNV+a4kD9nhdjoVJWviU=
    - secure: eaNg576UAG9cljY3sGtMLAZQPq/Taq9MXlMk57YyxUmvaxBNXM1Vv0gYOC1Xx6NYS8Kt9yaXVaNV46DXytV/SBmzn1I/oxAQNfhaB/sJof8qC1PiQNt0OxG7LofHrscGEX9/zO1GiVisQzCoJYWieQn/fw9OQ4MrrqOQ5C4AwJ96YDWGK9JBzf3XoHL9Yw2R0s6mQpNz/wQO01dn9HAlnPhCh8z2GsWdV8Olp6tv9v2nrrNcVwrG1NAV/V00KKzn4vSgtBxu/mNDjg19ZrXw0v120Go/3KyqsEQzFYpM4okl+1JbjtI4D97zK86/KnjE6u7ORL6ZIm+ucuhvgHEWAhCKFUDlbckIN1XRaNLmZSrE5nrCRg/d0M07TsZW9fjqS9FmvuKP3DqoCyklCSU0so11sG1yGLevaGKzD6Jkp+TPBi0zK+9m1/ZzEjT7XJIXanZ38rvZV8MmVPLnE7947SBQDOSNHum0GwyPYuMQi/F+3YlLdcuTZQAb2ahaLCn1r8yEofctnPwwYmbgDcLB4P9AsA1Yepx+Eze4sTPKzA1HbAJqWCtYa8vSX1GgQi28KaHF4TFPynCo5vwzCwoX/ONZB8iVk8xFeti09jVf+r96RQQcYOrbmBFM+Pzcs5OpU8Tg8ayJLS16Ng6bVWR8L1SrtsTS7fdeDuI/FrcAE2o=
branches:
  only:
  - master
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install -g karma
  - bower install
  - npm install
  - npm run build
