language: node_js
node_js:
  - "0.10"
branches:
  only:
  - master
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install -g karma
  - bower install
  - npm install
  - npm run build